### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [l15n/fish-tmbundle#1]
We would like to use your lexer at github/linguist#1785 to highlight fish code on GitHub but I don't know what licensing terms you're distributing it under.
Any chance you could pick one from here: http://choosealicense.com?

**Comment by l15n** [comment]
Thanks for contacting me. I'll choose a permissive license for this.

**Comment by ghost** [comment]
:+1: Awesome

**Comment by l15n** [comment]
Now using the MIT License

**Comment by pchaigno** [comment]
@l15n Thanks!
